# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dump-parser}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Markus Schirp}]
  s.date = %q{2011-09-11}
  s.description = %q{Provides an easy way to manage a huge amount of domain specific string2value conversions. Mostly useful to convert legacy CSV-Fields from strings with domain specific rules}
  s.email = %q{mbj@seonic.net}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "dump-parser.gemspec",
    "lib/dump-parser.rb",
    "spec/integration/dump-parser_spec.rb",
    "spec/quality/dump-parser_spec.rb",
    "spec/spec_helper.rb",
    "spec/unit/dsl_spec.rb",
    "spec/unit/dump_parser/class_methods/execute_spec.rb",
    "spec/unit/dump_parser/class_methods/has_parser_spec.rb",
    "spec/unit/dump_parser/class_methods/lookup_spec.rb",
    "spec/unit/dump_parser/class_methods/names_spec.rb",
    "spec/unit/dump_parser/class_methods/new_spec.rb",
    "spec/unit/dump_parser/class_methods/register_spec.rb",
    "spec/unit/dump_parser/class_methods/reset_spec.rb",
    "spec/unit/dump_parser_spec.rb"
  ]
  s.homepage = %q{http://github.com/mbj/dump-parser}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{Simple string2value DSL}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2"])
      s.add_development_dependency(%q<yard>, ["~> 0.7"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<reek>, ["~> 1.2"])
      s.add_development_dependency(%q<roodi>, ["~> 2.1"])
    else
      s.add_dependency(%q<rspec>, ["~> 2"])
      s.add_dependency(%q<yard>, ["~> 0.7"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<reek>, ["~> 1.2"])
      s.add_dependency(%q<roodi>, ["~> 2.1"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2"])
    s.add_dependency(%q<yard>, ["~> 0.7"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<reek>, ["~> 1.2"])
    s.add_dependency(%q<roodi>, ["~> 2.1"])
  end
end

